#!/bin/sh
if [ -z $JAVA_HOME ]
then
	echo "ERROR!! : JAVA_HOME environment variable must be set."
	exit -1
fi

if [ -z $JUNZIP_HOME ]
then
	echo "ERROR!! : JUNZIP_HOME environment variable must be set."
	exit -1
fi

# start execution
CLASSPATH=.
for jar in $JUNZIP_HOME/lib/*.jar
do
	CLASSPATH=$CLASSPATH:$jar
done

$JAVA_HOME/bin/java -cp $CLASSPATH net.kldp.junzip.JUnzipMain "$@"
